title: Workshop Docs
description: An in-depth documentation for developing User Generated Content for Jump King!
theme: just-the-docs

url: https://phoenixx19.github.io/jk-workshop-docs
favicon: /favicon.png

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
